language: c
sudo: required
os: linux
services:
  - docker

script:
  - docker build --build-arg tag=$TAG --build-arg switch=$SWITCH --tag colisanr/morbig:$TRAVIS_BRANCH .
  - docker run --entrypoint /bin/sh colisanr/morbig:$TRAVIS_BRANCH -c 'eval $(opam env) && cd /home/opam/morbig && make check && make install && make examples && make uninstall'

matrix:
  include:
    - os: osx
      osx_image: xcode12
      install:
        - brew install opam
        - opam init --no-setup
        - eval $(opam config env) && opam install --yes menhir yojson ppx_deriving_yojson visitors
      script:
        - make && make check && make install && make examples && make uninstall
    - env: TAG=4.04
    - env: TAG=4.05
    - env: TAG=4.06 DEPLOY=true
    - env: TAG=4.07
    - env: TAG=4.08
    - env: TAG=alpine
    - env: TAG=centos
    - env: TAG=debian-stable
    - env: TAG=debian-testing
    - env: TAG=debian-unstable
    - env: TAG=opensuse
    - env: TAG=ubuntu
    - env: TAG=ubuntu-lts

## We automatically deploy sucessfull branch builds to DockerHub. This
## deployment only happens on builds that have the environment
## variable DEPLOY set to true and in Travis repositories that set the
## variable TRAVIS_DEPLOY to true. The variables DOCKER_* are filled
## in on Travis.

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  skip_cleanup: true
  script: docker push colisanr/morbig:$TRAVIS_BRANCH
  on:
    branch: master
    condition:
      - $DEPLOY = true
      - $TRAVIS_DEPLOY = true
